# Generated by Django 5.1.6 on 2025-03-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
