# Generated by Django 5.1.6 on 2025-03-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(default=-1),
        ),
    ]
