# Generated by Django 5.1.6 on 2025-03-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offer_min_delivery_time_offer_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='min_delivery_time',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
