# Generated by Django 5.1.6 on 2025-03-19 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tel', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('working_hours', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('business', 'Geschäftsprofil'), ('customer', 'Kundenprofil')], max_length=20)),
                ('created_at', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
