# Generated by Django 5.1.6 on 2025-03-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_alter_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=200),
        ),
    ]
